# Generated by Django 5.0.6 on 2025-10-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkingLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=10)),
                ("total_spots", models.IntegerField(default=0)),
                ("electric_available", models.BooleanField(default=False)),
                ("disabled_available", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="parkingslot",
            name="lot_name",
            field=models.CharField(default="test lot", max_length=50),
            preserve_default=False,
        ),
    ]
