# Generated by Django 5.0.6 on 2025-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parking", "0002_parkinglot_parkingslot_lot_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkinglot",
            name="disabled_available",
        ),
        migrations.RemoveField(
            model_name="parkinglot",
            name="electric_available",
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="occupied_spots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="parkinglot",
            name="status",
            field=models.CharField(default="여유", max_length=20),
        ),
        migrations.AlterField(
            model_name="parkinglot",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="parkinglot",
            name="total_spots",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="parkingslot",
            name="lot_name",
            field=models.CharField(default="Default Lot", max_length=50),
        ),
    ]
